theme: jekyll-theme-midnight
title: Peace Georland ADIKPETO
description: Electrical Engineering Student | FPGA • Embedded Systems • Qt6/C++
url: "https://Peace-ADIKEPETO.github.io"
author: Peace Georland ADIKPETO
email: peaceadikpeto@gmail.com

# Social links
linkedin_username: peaceadikpeto
github_username: Peace-ADIKEPETO
